/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package affine.cipher.z;
import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author rsagr
 */
public class AffineCipherZAB extends javax.swing.JFrame {

    /**
     * Creates new form AffineCipherZAB
     */
    public AffineCipherZAB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Alpha");

        jLabel6.setText("Beta");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Encrypt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setText("Affine Cipher ZAB ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Select File");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Enter the value of Alpha, Beta and N (size of alphabet)");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jButton3.setText("Decrypt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel3.setText("N");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel7.setText("Encryptcion and decryption formula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(21, 21, 21)))
                                    .addComponent(jButton3))
                                .addGap(25, 25, 25))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(48, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)))
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(133, 133, 133)))))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(72, 72, 72))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 644, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3))
                                .addGap(19, 19, 19)))))
                .addGap(3, 3, 3)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(339, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a;
        int alpha,i;
        a = jTextField1.getText();
        alpha = Integer.parseInt(a);
        i = serch(alpha);
        if(i == -1){
            JOptionPane.showMessageDialog(rootPane, "Enter an other value of alpha\nThe value "+alpha+" is no accepted");
        }
        else
        encrypt();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //File Selection
        JFileChooser jf = new JFileChooser();
        int a = jf.showOpenDialog(null);
        System.out.println(a);
        if(a == JFileChooser.APPROVE_OPTION){
            FileReader bf = null;
            try {
                ff = jf.getSelectedFile();
                JOptionPane.showMessageDialog(rootPane, "Nombre del archivo \n" + ff.getName());
                //Lectura del archivo y escritura en la plantilla
                bf = new FileReader(ff);
                jTextArea2.read(bf, "");
            } catch (Exception ex) {
                Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    bf.close();
                } catch (IOException ex) {
                    Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Decryption method
        String a;
        int alpha,i;
        a = jTextField1.getText();
        alpha = Integer.parseInt(a);
        i = serch(alpha);
        if(i == -1){
            JOptionPane.showMessageDialog(rootPane, "Enter an other value of alpha\nThe value "+alpha+" is no accepted");
        }
        else
        decrypt();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

//Botom of decryption
    /*    */
    /**
     * @param args the command line arguments
     */
    File ff;
    String alphafet = "abcdefghijklmnopqrstuvwxyz";
    int[] alpha1 = {1,3,5,7,9,11,15,17,19,21,23,25}; 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffineCipherZAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffineCipherZAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffineCipherZAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffineCipherZAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffineCipherZAB().setVisible(true);
            }
        });
    }
    public int  inverse(int num,int module){
        int number = num + module;
        while (number < 0){
            number =number + module;
        }
        return number;
    }
    public int multiInverse(int num){
        int i = 0;
        for(i = 0; i < alpha1.length;i++){
            if((num * alpha1[i])%26 == 1){
                num = alpha1[i];
            }
        }
        return num;
    }
    public void encrypt(){
         PrintWriter EncryptOut = null;
        try {
            String a, b,line;
            //Funtion to write in the FILE
            EncryptOut = new PrintWriter("out.txt");
            int alpha, beta;
            a = jTextField1.getText();
            b = jTextField2.getText();
            if(a.matches("[0-9]+") && b.matches("[0-9]+")){
                alpha = Integer.parseInt(a);
                beta = Integer.parseInt(b);
                FileReader lectura = null;
                try {
                    JOptionPane.showMessageDialog(rootPane, "The entered value is \nalpha = "+alpha+"\nbeta =  "+beta);
                    lectura = new FileReader(ff);
                    BufferedReader buffer = new BufferedReader(lectura);
                    StringBuilder cadena = new StringBuilder();
                    int i,p;
                    while((line = buffer.readLine()) != null){
                        //here where the algorithm takes action
                        line = line.toLowerCase();
                        for(i = 0; i < line.length(); i++){
                            p = alphafet.indexOf(line.charAt(i));
                            if(p != -1){
                                cadena.append(alphafet.charAt(((alpha)*(p) + beta)%26));
                            }
                        }
                        System.out.println(cadena.toString().toUpperCase());
                        EncryptOut.write(cadena.toString().toUpperCase());
                        //salidaCifrada.println();
                        cadena.setLength(0);
                    }
                    EncryptOut.flush();
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(rootPane,"File not found");
                } catch (IOException ex) {
                    Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        lectura.close();
                    } catch (IOException ex) {
                        Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Invalid data, please enter numeric values");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            EncryptOut.close();
        }
        ff = new File("out.txt");
        //Write in the jTextArea1
        if(ff.getPath() != null){
            try {
                FileReader bf = null;
                bf = new FileReader(ff);
                try {
                    jTextArea1.read(bf, "");
                } catch (IOException ex) {
                    Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                try {
                    bf.close();
                } catch (IOException ex) {
                    Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    public void decrypt(){
        System.out.println(ff.getPath());
        PrintWriter EncryptOut = null;
        try {
            String a, b,line;
            //Funtion to write in the FILE
            EncryptOut = new PrintWriter("outDecrypt.txt");
            int alpha, beta,index;
            a = jTextField1.getText();
            b = jTextField2.getText();
            if(a.matches("[0-9]+") && b.matches("[0-9]+")){
                FileReader lectura = null;
                try {
                    alpha = Integer.parseInt(a);
                    beta = Integer.parseInt(b);
                    JOptionPane.showMessageDialog(rootPane, "The entered value is \nalpha = "+alpha+"\nbeta =  "+beta);
                    //INVERSO ADITIVO 
                    beta = inverse(-beta,26);
                    //INVERSO MULTIPLICATIVO 
                    System.out.println("Inverso Multi");
                    index = serch(alpha);
                    alpha = multiInverse(alpha);
                    lectura = new FileReader(ff);
                    BufferedReader buffer = new BufferedReader(lectura);
                    StringBuilder cadena = new StringBuilder();
                    int i,p;
                    while((line = buffer.readLine()) != null){
                        //here where the algorithm takes action
                        line = line.toLowerCase();
                        for(i = 0; i < line.length(); i++){
                            p = alphafet.indexOf(line.charAt(i));
                            if(p != -1){
                                cadena.append(alphafet.charAt(((alpha)*((p) + beta))%26));
                            }
                        }
                        System.out.println(cadena.toString().toLowerCase());
                        EncryptOut.write(cadena.toString().toLowerCase());
                        //salidaCifrada.println();
                        cadena.setLength(0);
                    }
                    EncryptOut.flush();
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(rootPane,"File not found");
                } catch (IOException ex) {
                    Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        lectura.close();
                    } catch (IOException ex) {
                        Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Invalid data, please enter numeric values");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            EncryptOut.close();
        }
        ff = new File("outDecrypt.txt");
        //Write in the jTextArea1
        if(ff.getPath() != null){
            try {
                FileReader bf = null;
                bf = new FileReader(ff);
                try {
                    jTextArea1.read(bf, "");
                } catch (IOException ex) {
                    Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                try {
                    bf.close();
                } catch (IOException ex) {
                    Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AffineCipherZAB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    public int serch(int alpha){
        int index = -1,i;
        for(i = 0; i < alpha1.length; i++){
            if(alpha1[i] == alpha){
                index = i;
            }
        }
        return index;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
